<a href="https://colab.research.google.com/github/omarrayyann/Learning/blob/main/Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [8]:
# tensor examples
tensor_example = tf.Variable([["ahmad","omar"], ["emad","ali"]], tf.string)
tensor_example.shape

TensorShape([2, 2])

In [17]:
# tensor reshaping
tensor1 = tf.ones([1,2,3]); # the [1,2,3] is the shape
print(tensor1)
tensor1 = tf.reshape(tensor1, [1,-1]) # -1 infer the required number given the number of points in the tensor
print(tensor1)
# multiplying the numbers in the rank with each other gives the number of data points (subbets data points)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor([[1. 1. 1. 1. 1. 1.]], shape=(1, 6), dtype=float32)
